### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by AleSarick** [Chun-Lin/Taiwan-Railway-Booking-System#1]
I got the error when connected but didn't exactly know what's going on here 

      throw new Error(err.message);
      ^

Error: read ECONNRESET
    at Socket.socket.on (D:\Ticket\Taiwan-Railway-Booking-System-master\scrapers\2019railway\deathbycaptcha.js:340:13)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by Chun-Lin** [comment]
Looks like DBC socket server is not stable right now, I changed it to http client and it should be fine now.
